FROM ras_base:ras_local AS builder

RUN apt-get install lsb-release wget gnupg curl -y
RUN wget https://packages.osrfoundation.org/gazebo.gpg -O /usr/share/keyrings/pkgs-osrf-archive-keyring.gpg
RUN echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/pkgs-osrf-archive-keyring.gpg] http://packages.osrfoundation.org/gazebo/ubuntu-stable $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/gazebo-stable.list > /dev/null
RUN apt-get update
RUN apt-get install -y ignition-fortress

RUN mkdir -p /ras_server_app

RUN pip install boto3 awsiotsdk

RUN echo "source /ras_server_app/scripts/env.sh" >> /etc/bash.bashrc


WORKDIR /
SHELL ["/bin/bash","-c"]
USER ras
RUN curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.0/install.sh | bash \
    && . ~/.nvm/nvm.sh \
    && nvm install 20 -y
RUN python3 -m pip install flask pyftpdlib paho-mqtt
USER root
RUN apt install software-properties-common -y && \ 
    apt-add-repository ppa:mosquitto-dev/mosquitto-ppa -y && \
    apt-get update &&  apt install mosquitto -y
RUN touch ~/.tmux.conf && echo "set -g mouse on" >> ~/.tmux.conf

RUN pip install openai

CMD ["sleep", "infinity"]