lab_setup:
  lab_name: "oss_lab1"  # Name of the lab environment

  # Choose the simulation environment
  # "aruco_world" includes perception but is significantly slower
  # "oss_lab1" runs without perception for faster performance
  real_sim: "oss_lab1"

  robot_name: "xarm_lite6"  # Primary robot in the setup
  robot_config_file: "robots/{robot_name}.yaml"
 
