lab_setup:
  lab_name: "oss_lab1"
  real_sim: "aruco_world"
  robot:
      name: "xarm_lite6"
      pose:
          x: -1.239280
          y: -3.298410
          z: 1.120070
          roll: 0.0
          pitch: 0.0
          yaw: -1.57