ras:
  real:
    # sim: true
    # real: false
    mode: real # sim or real
  transport:
    implementation: default
    ftp:
      sim:
        ip: localhost
        port: 2121
      real:
        ip: localhost
        port: 2122
    mqtt:
      ip: localhost
      port: 2383
