ras:
  transport:
    implementation: default
    file_server:
      server:
        ip: localhost
        port: 2121
      robot:
        ip: localhost
        port: 2122
    mqtt:
      ip: localhost
      port: 2383
