ras:
  transport:
    implementation: default
    file_server:
      use_external: true
      ip: dev2.deepklarity.ai
      port: 9501
    mqtt:
      use_external: true
      ip: dev2.deepklarity.ai
      port: 9500
